* Dotbot =brew= plugin
:PROPERTIES:
:ID:                     52d1c964-770e-4844-8ab4-2f7f395d97c7
:END:

#+CAPTION: Integration test status
#+NAME:   fig:INT-TESTS
[[https://github.com/d12frosted/dotbot-brew/workflows/macOS/badge.svg]]

Plugin for [[https://github.com/anishathalye/dotbot][dotbot]] that adds =brew=, =brewfile=,
and =cask= directives. It allows installation of packages using =brew= and =brew cask= on macOS.

In case =brew= is not installed, it will be automatically loaded and configured.
The plugin itself is pretty silly as it doesn't handle updates and fails on unsupported
operating systems.

** Note for ARM (Apple Silicon) Macs

If you're on an ARM mac, you probably want to force to run the Intel version of Homebrew
since the ARM version is still not fully functional and buggy, so you can add the
=- force_intel: true= option to defaults.

** Installation
:PROPERTIES:
:ID:                     597691cd-5651-400f-ada0-a68454d7825a
:END:

Just add it as submodule of your dotfiles repository.

#+BEGIN_SRC shell
git submodule add https://github.com/d12frosted/dotbot-brew.git
#+END_SRC

Modify your =install= script, so it automatically enables =brew= plugin.

#+BEGIN_SRC shell
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
#+END_SRC

** Usage
:PROPERTIES:
:ID:                     2e816835-29cf-4747-8d19-9db69717f515
:END:

In your =install.conf.yaml= use =brew= directive to list all packages to be
installed using =brew=. The same works with =cask= and =brewfile=. For example:

#+BEGIN_SRC yaml
- brewfile:
    - Brewfile
    - brew/Brewfile

- tap:
    - caskroom/fonts

- brew:
    - git
    - git-lfs
    - emacs --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --HEAD --use-git-head

- brew: [gnupg, gnupg2]

- cask: [colorpicker, vlc]
#+END_SRC

Defaults also can control stdin, stdout and stderr (disabling with false, enabling with true),
see below for an example

#+BEGIN_SRC yaml
- defaults:
    - brewfile:
        - stdin: true
        - stdout: true
        - stderr: true

- brewfile:
    - Brewfile
    - brew/Brewfile

- tap:
    - caskroom/fonts

- brew:
    - git
    - git-lfs
    - emacs --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --HEAD --use-git-head

- brew: [gnupg, gnupg2]

- cask: [colorpicker, vlc]
#+END_SRC
