#!/usr/bin/env bash

package="$1"
cask="$2"
brewBrewfile="$3"
tapBrewfile="$4"
caskBrewfile="$5"
dotfiles=$(mktemp -d)

cd "$dotfiles" && {
  git init
  git submodule add https://github.com/anishathalye/dotbot
  git submodule add https://github.com/d12frosted/dotbot-brew.git

  git config -f .gitmodules submodule.dotbot.ignore dirty

  # copy install script
  cp dotbot/tools/git-submodule/install .

  # patch installation to support dotbot-brew
  sed -i -e "s/-c/--plugin-dir dotbot-brew -c/g" "install"

  echo -n > Brewfile
  echo 'tap "$tapBrewfile"' >> Brewfile
  echo 'cask "$caskBrewfile"' >> Brewfile
  echo 'brew "$brewBrewfile"' >> Brewfile

  echo -n > install.conf.yaml
  echo "- installBrew: [brew, cask]" >> install.conf.yaml
  echo "- brew: [$package]" >> install.conf.yaml
  echo "- cask: [$cask]" >> install.conf.yaml
  echo "- brewfile: [Brewfile]" >> install.conf.yaml

  ./install --verbose
}
