#!/usr/bin/env bash

set -e

os="$1"

echo "create a temporary dotfiles directory at $dotfiles"
dotfiles=$(mktemp -d)

echo "copy install configurations"
cp "examples/$os/example.yaml" "$dotfiles/install.conf.yaml"
cp "examples/$os/Brewfile" "$dotfiles/Brewfile"

echo "copy dotbot-brew"
cp -r "." "$dotfiles/dotbot-brew"

cd "$dotfiles" && {
  echo "initialize repository"
  git init
  git submodule add https://github.com/anishathalye/dotbot

  git config -f .gitmodules submodule.dotbot.ignore dirty

  echo "copy install script"
  cp dotbot/tools/git-submodule/install .

  echo "patch installation to support dotbot-brew"
  sed -i -e "s/-c/--plugin-dir dotbot-brew -c/g" "install"

  echo "content of install.conf.yaml"
  cat install.conf.yaml

  echo "install all packages"
  ./install
}
